### Site Settings ###
title               : My Portfolio
description         : >-
                      Hello! My name is Katerina and this is my portfolio site. 
                      Head on over to my [about page](https://kattaque.github.io/portfolio/about/) to learn more about me, 
                      or puruse my [projects page](https://kattaque.github.io/portfolio/projects/) to see what work I've done previously.
baseurl             : "/portfolio"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : kattaque/kattaque.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Katerina Wu
  image             : https://64.media.tumblr.com/4dd631d3814387fb6a967f13034a8e3b/tumblr_pgg6ptVgUL1tfpvc0o1_500.jpg
# behance           : your_username
# dribbble          : your_username
  email             : klwu072@gmail.com
# facebook          : your_username
  github            : kattaque
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : katerina-wu-736241127
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : kattaqueue
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
